---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - letsencrypt_acme
  register: container_facts

- name: Checking free port for LetsEncrypt server
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ letsencrypt_acme_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['letsencrypt_acme'] is not defined
    - inventory_hostname in groups['letsencrypt_acme']
