---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tunelo_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: tunelo_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/tunelo/"
      skip: true

- name: Set tunelo policy file
  set_fact:
    tunelo_policy_file: "{{ tunelo_policy.results.0.stat.path | basename }}"
    tunelo_policy_file_path: "{{ tunelo_policy.results.0.stat.path }}"
  when:
    - tunelo_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tunelo_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over tunelo.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/tunelo.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/tunelo.conf"
      - "{{ node_custom_config }}/tunelo/{{ item.key }}.conf"
      - "{{ node_custom_config }}/tunelo/{{ inventory_hostname }}/tunelo.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/tunelo.conf"
    mode: "0660"
  become: true
  when:
    - item.key in [ "tunelo-api" ]
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tunelo_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over existing policy file
  vars:
    services_require_policy_json:
      - tunelo-api
  template:
    src: "{{ tunelo_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ tunelo_policy_file }}"
    mode: "0660"
  become: true
  when:
    - tunelo_policy_file is defined
    - item.key in services_require_policy_json
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tunelo_services }}"
  notify:
    - "Restart {{ item.key }} container"
