---
- import_tasks: register.yml
  when: enable_keystone | bool

- import_tasks: config.yml

- import_tasks: check-containers.yml

- include_tasks: clone.yml
  when: tunelo_dev_mode | bool

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers
